### ISSUE TITLE
Include all the controls to the reader page.

### ISSUE THREAD

**Issue by mateus** [mateus/Contentify#15]
WIP Mocks: https://marvelapp.com/5ba75f0/screen/27271753

@kaigenji I think we should provide these controls on the reader page as well.
👇 
<img width="216" alt="screen shot 2017-04-20 at 8 02 58 pm" src="https://cloud.githubusercontent.com/assets/2091116/25257214/60d55db8-2604-11e7-8e40-bde78c978cdf.png">

Currently we only have the font size control.
👇 
<img width="704" alt="screen shot 2017-04-20 at 8 01 45 pm" src="https://cloud.githubusercontent.com/assets/2091116/25257194/42d951ca-2604-11e7-9e4e-84ee0754d2a1.png">

**Comment by kaigenji** [comment]
I agree. I'll come up with a design to fix these issue.
